### PR TITLE
Mini aod 8 0 18

### PR DESCRIPTION
**Pull request by alfloren**
Efficiency resolution updated to mini-AOD and background shape fit added

### CODE REVIEW

**Comment by Fedespring** [comment]
Ciao Alice, 
I didn't test the code but just looking at the modifications, I was wondering why did you change the name of the process to leptonsMini? Now Nminus module cannot work, so please do another PR to fix this file:
https://github.com/cms-analysis/SUSYBSMAnalysis-Zprime2muAnalysis/blob/mini-AOD/test/NMinus1Effs/nminus1effs.py

Thanks,
Federica

**Comment by alfloren** [comment]
Hi Fede,

Sure i will fix this file. 
I changed to leptonsMini because as soon as you want to put the process in a sequence the _ is a problem, so in general rule we should not define process with _ inside.
So indeed better change the name of the process in N-1 as i did for hits.py inside DataMC and inside EffReso, i just forgot that it was in N-1.

Thanks for spotting it,

Alice

**Comment by rradogna** [comment]
Hi Alice,

please don’t touch too many files. Better to keep _mini and to clone it, as done in N-1 and DataMC. If you clone it you can call it as you wish and it will work.

I simply say this because all other packages are well tested, we don’t really need to change this in all of them. You can do a simple clone in Efficiency.

Cheers,
Raffaella

> Il giorno 19 nov 2016, alle ore 17:48, alfloren notifications@github.com ha scritto:
> 
> Hi Fede, 
> 
> Sure i will fix this file. 
> I changed to leptonsMini because as soon as you want to put the process in a sequence the _ is a problem, so in general rule we should not define process with _ inside. 
> So indeed better change the name of the process in N-1 as i did for hits.py inside DataMC and inside EffReso, i just forgot that it was in N-1. 
> 
> Thanks for spotting it, 
> 
> Alice 
>

**Comment by alfloren** [comment]
Hi Raffaella,

I knew you will say that ;)
But it has nothing to do with the clone. I did clone as you did for N-1. 
Here it is simply if you want to define in others file in sequence and call it from another python.

There is really basically nothing too change, it is one line of code in N-1 which consist when you clone the process to put leptonMini instead of lepton_mini.

I don’t think we should question this choice. It is not correct to have a _ in a process name and it can be a problem in the future, each time we want to create a sequence. 
So i prefer to change the name instead of keeping things that we know are not optimal just because somebody made a wrong choice at the beginning.

I hope you agree, if so then I will update n-1.

Alice

**Comment by rradogna** [comment]
Hi alice,

My comment was a general comment. Better to change less files as possible.
If you think that changing the process name everywhere is the only possible
solution, please go ahead.

Best,
Raffaella
Il 21/nov/2016 10:11 "alfloren" notifications@github.com ha scritto:

**Comment by alfloren** [comment]
Hi Raffaella,

I think it is the cleaner solution. But of course i understand your point. I believe only changing one line will be enough.
I will try in my version and make a pull request if the changes are minimal. Otherwise i will let you know.

Thanks for the feedback,

Alice

**Pull request closed without merging**
