### PR TITLE
Updates to latest muon selection, adding support for dielectron analysis, some CI stuff, and new interface to execute the analysis

### PR DESCRIPTION
**Pull request by JanFSchulte**
This PR adds a few updates to the muon anylsis (latest matching station cut), but is mostly concerned with making the framework more useful for the CI analysis by

- adding a more user-friendly interface to actually run things
- adding support for dielectron pairs (synchronized to the <<<% level with Wenxing for 2017) so we need only one framework for the CI

All changes should be ~transparent for current users.

### CODE REVIEW

**Comment by khaosmos93** [comment]
Locally tested in CMSSW_10_2_7. Complied and run without any errors.
Since all the new selections are implemented in "python/OurSelection2017_cff.py", I think we can remove "python/OurSelection2018_cff.py" in order to avoid any confusion. What do you think? @JanFSchulte @BenjaminRS @cschnaible

**Comment by JanFSchulte** [comment]
I have updated a few things to integrate PU reweighting for the electron channel. (can very simply be applied for muons as well if desired), added a few histograms, and improved the running of crab jobs by enabling the ignoreLocality feature for samples present on <= 1 T2 sites. 

@khaosmos93 We have to decide which name we like more I guess, the selection is technically a 2018 one, so changing the name of my config to 2018 might be most intuitive.

**Review by cschnaible — APPROVED** [review]
Given that Min was able to compile and run without any errors I do not have any problems with this PR. It has some nice new features and necessary updates.

**Comment by cschnaible** [comment]
I should also say thanks to Jan for putting this PR together.

**Comment by BenjaminRS** [comment]
Hi - were the bug fixes checked? Or are they straight forward enough to sign off on?

**Comment by cschnaible** [comment]
The bug fixes in the commits are simple enough to not need any additional checking.

**Comment by BenjaminRS** [comment]
ok please go ahead and merge

**Pull request merged**
